apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Replace=false
    keycloak.org/realm-import-configmap: backstage-realm-config
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: true
  ingress:
    enabled: true
    tls:
      secretName: rhbk-tls-secret
  http:
    tlsSecret: rhbk-tls-secret
  hostname:
    hostname: keycloak.apps.cluster-brl4w.brl4w.sandbox968.opentlc.com