apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakUser
metadata:
  name: developer-1
  namespace: keycloak
spec:
  user:
    username: developer1
    enabled: true
    email: developer1@example.com
    firstName: Dev
    lastName: One
    credentials:
      - type: password
        value: developer123
    realmRoles:
      - developer
  realmRef:
    name: backstage-realm

---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakUser
metadata:
  name: developer-2
  namespace: keycloak
spec:
  user:
    username: developer2
    enabled: true
    email: developer2@example.com
    firstName: Dev
    lastName: Two
    credentials:
      - type: password
        value: developer123
    realmRoles:
      - developer
  realmRef:
    name: backstage-realm

---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakUser
metadata:
  name: platform-engineer-1
  namespace: keycloak
spec:
  user:
    username: platform1
    enabled: true
    email: platform1@example.com
    firstName: Platform
    lastName: One
    credentials:
      - type: password
        value: platform123
    realmRoles:
      - platform-engineer
  realmRef:
    name: backstage-realm
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakUser
metadata:
  name: platform-engineer-2
  namespace: keycloak
spec:
  user:
    username: platform2
    enabled: true
    email: platform2@example.com
    firstName: Platform
    lastName: Two
    credentials:
      - type: password
        value: platform123
    realmRoles:
      - platform-engineer
  realmRef:
    name: backstage-realm