apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealm
metadata:
  name: backstage-realm
  namespace: keycloak
spec:
  realm:
    id: backstage
    realm: backstage
    displayName: Developer Hub Realm
    enabled: true
  instanceRef:
    name: keycloak