apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: backstage-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    from:
      configMap:
        name: backstage-realm
        key: backstage-realm.json