apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: keycloak-realm
  namespace: keycloak
  labels:
    app.kubernetes.io/instance: keycloak-realm
spec:
  keycloakCRName: keycloak
  realm:
    from:
      configMap:
        name: backstage-realm-config
        key: backstage-realm.json