apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: backstage-realm-import
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    $import: /realm/backstage-realm.json