gitlab:
  image: quay.io/redhat-gpte/gitlab:17.4.1

  host: "gitlab-gitlab.apps.cluster-htghs.htghs.sandbox440.opentlc.com"
  https: "true"

  email:
    address: "gitlab@apps.cluster-htghs.htghs.sandbox440.opentlc.com"
    displayName: "GitLab Admin"
    replyTo: "noreply@apps.cluster-htghs.htghs.sandbox440.opentlc.com"
  rootEmail: "root@apps.cluster-htghs.htghs.sandbox440.opentlc.com"

  rootPassword: "backstage"

  keyBase:
    db: "0123456789"
    otp: "0123456789"
    secret: "0123456789"
  
  ssh:
    host:
    port: "22"

  smtp:
    enabled: "false"
    domain: "rhdemo.com"
    host:
    port: "587"
    user: "gitlab"
    password: "gitlab"

  users:
    count: 0

  groups:
    - name: rhdh

postgresql:
  dbUser: gitlab
  dbPassword: passw0rd
  dbName: gitlab_production

cluster:
  subdomain: "apps.cluster-htghs.htghs.sandbox440.opentlc.com"

orchestrator:
  namespace: orchestrator
