gitlab:
  image: quay.io/redhat-gpte/gitlab:17.4.1

  host: "gitlab-gitlab.apps.cluster-htghs.htghs.sandbox440.opentlc.com"
  https: "true"

  email:
    address: "gitlab@apps.cluster-htghs.htghs.sandbox440.opentlc.com"
    displayName: "GitLab Admin"
    replyTo: "noreply@apps.cluster-htghs.htghs.sandbox440.opentlc.com"
  rootEmail: "root@apps.cluster-htghs.htghs.sandbox440.opentlc.com"

  rootPassword: ""

  keyBase:
    db: "0123456789"
    otp: "0123456789"
    secret: "0123456789"
  
  ssh:
    host:
    port: "22"

  smtp:
    enabled: "false"
    domain: "rhdemo.com"
    host:
    port: "587"
    user: "gitlab"
    password: "gitlab"

  omniauth:
    enabled: true
    autoSignInWithProvider: "openid_connect"
    allowSingleSignOn: ["openid_connect"]
    blockAutoCreatedUsers: false
    externalProviders: ["openid_connect"]
    providers:
      - name: "openid_connect"
        label: "Keycloak"
        args:
          name: "openid_connect"
          scope: ["openid", "profile", "email", "groups"]
          response_type: "code"
          issuer: "https://keycloak.apps.cluster-htghs.htghs.sandbox440.opentlc.com/realms/backstage"
          discovery: true
          client_auth_method: "query"
          uid_field: "preferred_username"
          client_options:
            identifier: "gitlab"
            secret: "gitlab-client-secret"
            redirect_uri: "https://gitlab-gitlab.apps.cluster-htghs.htghs.sandbox440.opentlc.com/users/auth/openid_connect/callback"

  users:
    count: 0

  groups:
    - name: rhdh

postgresql:
  dbUser: gitlab
  dbPassword: passw0rd
  dbName: gitlab_production

cluster:
  subdomain: "apps.cluster-htghs.htghs.sandbox440.opentlc.com"

orchestrator:
  namespace: orchestrator