gitlab:
  image: quay.io/redhat-gpte/gitlab:17.4.1

  host: "{{ GITLAB_HOSTNAME }}"
  https: "true"

  email:
    address: "gitlab@rhdemo.com"
    displayName: "GitLab Admin"
    replyTo: "noreply@rhdemo.com"
  rootEmail: "root@rhdemo.com"

  rootPassword: ""

  oidc:
    enabled: true
    clientId: gitlab
    clientSecret: ""
    issuer: "https://{{ KEYCLOAK_HOSTNAME }}/realms/backstage"
    redirectUri: "https://{{ GITLAB_HOSTNAME }}/users/auth/openid_connect/callback"
    scope: "openid profile email groups"
    userIdAttribute: "preferred_username"
    userNameAttribute: "name"
    groupsAttribute: "groups"

  groups:
    - name: rhdh
  
postgresql:
  dbUser: gitlab
  dbPassword: passw0rd
  dbName: gitlab_production

cluster:
  subdomain: "{{ OPENSHIFT_BASE_DOMAIN }}"

orchestrator:
  namespace: orchestrator