apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
         - name: developer-hub-config
      extraFiles:
        - name: rbac-policy-volume
          mountPath: /opt/app-root/src/rbac
          configMap:
            name: rbac-policy
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true