apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
         - name: developer-hub-config
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: false