apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
         - name: developer-hub-config
    podTemplate:
      spec:
        containers:
          - name: backstage
            env:
              - name: NODE_TLS_REJECT_UNAUTHORIZED
                value: "0"
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true