apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-hub
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/panchoraposo/developer-hub.git
    targetRevision: main
    path: apps/developer-hub/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 