apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/panchoraposo/developer-hub.git
    targetRevision: main
    path: apps/jenkins/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true