app:
  title: Backstage on OpenShift

backend:
  baseUrl: http://backstage-developer-hub.backstage.svc.cluster.local:7007
  listen:
    port: 7007
    host: 0.0.0.0

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
