app:
  title: Backstage on OpenShift

backend:
  cors:
    origin: 'https://backstage-developer-hub-backstage.apps.cluster-wcw7c.wcw7c.sandbox432.opentlc.com'
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  baseUrl: http://backstage-developer-hub.backstage.svc.cluster.local:7007
  listen:
    port: 7007
    host: 0.0.0.0

permission:
  enabled: true
  policy: plugin

auth:
#  providers:
#    guest:
#      dangerouslyAllowOutsideDevelopment: true
  environment: production
  providers:
    keycloak:
      production:
        clientId: backstage
        clientSecret: x2KHIVnsODqQEkkOlPXRBSrp90IQbmYf
        issuer: https://keycloak.apps.cluster-wcw7c.wcw7c.sandbox432.opentlc.com/realms/backstage
signInPage: keycloak

catalog:
  providers:
  ## --- KEYCLOAK_CATALOG_PROVIDERS ---
    keycloakOrg:
      default:
        baseUrl: https://keycloak.apps.cluster-wcw7c.wcw7c.sandbox432.opentlc.com/
        loginRealm: backstage
        realm: backstage
        clientId: backstage
        clientSecret: x2KHIVnsODqQEkkOlPXRBSrp90IQbmYf
        schedule:
          frequency: { minutes: 2 }
          timeout: { minutes: 1 }
          initialDelay: { seconds: 15 }
  ## --- KEYCLOAK_CATALOG_PROVIDERS ---