app:
  title: Backstage on OpenShift

backend:
  baseUrl: https://backstage-developer-hub-backstage.apps.cluster-wcw7c.wcw7c.sandbox432.opentlc.com
  listen:
    port: 7007
    host: 0.0.0.0

# --- AUTHENTICATION ---
## Development configuration
# auth:
#   providers:
#     guest:
#      dangerouslyAllowOutsideDevelopment: true

## Configuration required to enable OpenID Connect authentification
auth:
  session:
    secret: ${BACKEND_SECRET}
  environment: production
  providers:
    oidc:
      production:
        prompt: auto
        metadataUrl: https://keycloak.apps.cluster-wcw7c.wcw7c.sandbox432.opentlc.com/realms/backstage/.well-known/openid-configuration
        clientId: backstage
        clientSecret: x2KHIVnsODqQEkkOlPXRBSrp90IQbmYf
        signIn:
          resolvers:
            - resolver: preferredUsernameMatchingUserEntityName
signInPage: oidc
catalog:
  providers:
  ## --- KEYCLOAK_CATALOG_PROVIDERS ---
    keycloakOrg:
      default:
        baseUrl: https://keycloak.apps.cluster-wcw7c.wcw7c.sandbox432.opentlc.com/
        loginRealm: backstage
        realm: backstage
        clientId: backstage
        clientSecret: x2KHIVnsODqQEkkOlPXRBSrp90IQbmYf
        schedule:
          frequency: { minutes: 2 }
          timeout: { minutes: 1 }
          initialDelay: { seconds: 15}
  ## --- KEYCLOAK_CATALOG_PROVIDERS ---