app:
  title: Backstage on OpenShift

backend:
  baseUrl: https://backstage-developer-hub-backstage.<WILDCARD_APPS_OPENSHIFT>
  listen:
    port: 7007
    host: 0.0.0.0

# --- AUTHENTICATION ---
## Development configuration
# auth:
#   providers:
#     guest:
#      dangerouslyAllowOutsideDevelopment: true

## Configuration required to enable OpenID Connect authentification
auth:
  session:
    secret: ${BACKEND_SECRET}
  environment: production
  providers:
    oidc:
      production:
        prompt: auto
        metadataUrl: https://keycloak.{openshift_cluster_ingress_domain}/realms/backstage/.well-known/openid-configuration
        clientId: ${OAUTH_CLIENT_ID}
        clientSecret: ${OAUTH_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: preferredUsernameMatchingUserEntityName

signInPage: oidc

catalog:
  providers:
  ## --- KEYCLOAK_CATALOG_PROVIDERS ---
    keycloakOrg:
      default:
        baseUrl: https://keycloak.{openshift_cluster_ingress_domain}
        loginRealm: backstage
        realm: backstage
        clientId: ${OAUTH_CLIENT_ID}
        clientSecret: ${OAUTH_CLIENT_SECRET}
        schedule:
          frequency: { minutes: 2 }
          timeout: { minutes: 1 }
          initialDelay: { seconds: 15}
  ## --- KEYCLOAK_CATALOG_PROVIDERS ---