apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  namespace: backstage
spec:
  application:
    configMapRef: developer-hub-config
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true