apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-hub-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: Demo Red Hat Developer Hub
    organization:
      name: Red Hat
    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
        host: 0.0.0.0 
    