resources:
  - ../../base
  - dynamic-plugins-rhdh.yaml
  
configMapGenerator:
  - name: developer-hub-config
    files:
      - app-config.yaml
    options:
      disableNameSuffixHash: true

  - name: cluster-config
    envs:
      - cluster.env

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: openshift_cluster_ingress_domain
    objref:
      kind: ConfigMap
      name: cluster-config
      apiVersion: v1
    fieldref:
      fieldpath: data.OPENSHIFT_CLUSTER_INGRESS_DOMAIN