resources:
  - ../../base
  - dynamic-plugins-rhdh.yaml
  - rbac-policy.yaml

configMapGenerator:
  - name: developer-hub-config
    files:
      - app-config.yaml
    options:
      disableNameSuffixHash: true
  #- name: rbac-policy
  #  files:
  #    - rbac-conditional-policies.yaml
  #    - rbac-policy.csv

generatorOptions:
  disableNameSuffixHash: true