apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-custom-config
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
data:
  app-config-rhdh.yaml: |
    dynamic:
      includes:
        - dynamic-plugins.default.yaml
      plugins:
        - package: oci://quay.io/evanshortiss/backstage-plugin-scaffolder-backend-module-gitlab-dynamic:0.8.1!backstage-plugin-scaffolder-backend-module-gitlab
          disabled: false
        - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
          disabled: false
        - package: ./dynamic-plugins/dist/backstage-community-plugin-topology
          disabled: false