kind: Secret
apiVersion: v1
metadata:
  name: {{ include "redhat-developer-hub-prereqs.name" . }}-postgresql
  labels:
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
stringData:
  postgres-password: {{ .Values.backstage.postgresql.password }}
type: Opaque